2024-02-19 09:50:20,617 - build - main - ERROR - No such file found: /mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/wflow_hydrography/*.tif
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hydromt/cli/main.py", line 207, in build
    mod.build(region, opt=opt)
  File "/usr/local/lib/python3.10/dist-packages/hydromt/models/model_api.py", line 220, in build
    self._run_log_method(method, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hydromt/models/model_api.py", line 163, in _run_log_method
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hydromt_wflow/wflow.py", line 182, in setup_basemaps
    ds_org = self.data_catalog.get_rasterdataset(hydrography_fn)
  File "/usr/local/lib/python3.10/dist-packages/hydromt/data_catalog.py", line 707, in get_rasterdataset
    obj = source.get_data(
  File "/usr/local/lib/python3.10/dist-packages/hydromt/data_adapter/rasterdataset.py", line 263, in get_data
    fns = self.resolve_paths(
  File "/usr/local/lib/python3.10/dist-packages/hydromt/data_adapter/data_adapter.py", line 390, in resolve_paths
    raise FileNotFoundError(f"No such file found: {path}{postfix}")
FileNotFoundError: No such file found: /mnt/CEPH_PROJECTS/InterTwin/hydrologic_data/wflow_hydrography/*.tif
